version: '2'
services:
    php:
        container_name: laravel10_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /var/www
        volumes:
            -   ./:/var/www/
        networks:
            - app-network
        depends_on:
            -   mysql
    nginx:
        container_name: laravel10_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            -   ./:/var/www/
        working_dir: /var/www
        ports:
            -   8090:80
        networks:
            - app-network
        depends_on:
            -   php
    mysql:
        container_name: laravel5_mysql
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: thang
            MYSQL_PASSWORD: thang
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        networks:
            - app-network
    phpmyadmin:
        container_name: laravel5_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - app-network
        depends_on:
            -   mysql
networks:
    app-network:
        driver: bridge
